micropython/examples/pico_display/demo.py
Not ready to merge straight away, fixes the picodisplay micropython example issue.
The Ball class is still an issue though, will have a crack at it tomorrow...
Signed-off-by: James Sutton <1068763+jpwsutton@users.noreply.github.com>
=> Fixing buffer in picodisplay micropython example: Issue #9

.github/workflows/cmake.yml, .github/workflows/micropython.yml
This is a basic workflow config for:
1. Building  C++ libraries (the whole project)
2. Building micropython linked against our micropython ports of libraries
3. Attaching the .uf2 file to releases
Further TODO can be found here: #19
=> Github Actions Workflow

libraries/pico_display/README.md, libraries/pico_explorer/README.md, libraries/pico_graphics/README.md, libraries/pico_rgb_keypad/README.md, libraries/pico_unicorn/README.md, micropython/examples/pico_unicorn/demo.py, micropython/modules/pico_display/README.md, micropython/modules/pico_unicorn/README.md
Opened this for visibility - expands upon ede389d7af068197668ee85be2eaa0aa0985afc8 and starts to introduce API docs.
Still honing in on a style/voice here, but I have a strong preference for table-of-contents (make sure you have VSCode Markdown: All In one installed) and succinct examples/use cases to frame functions and types in context.
Some images would be really cool here, too,  specifically for the Pico Graphics library to illustrate things like clipping bounds, intersections, etc.
=> Documentation

README.md, libraries/pico_display/README.md
Typos prevented compilation if used as a base!
=> Corrected minor typos in README.md for the display libs

micropython/modules/pico_display/README.md
=> Typo Correction in MicroPython Display Doc

micropython/modules/pico_display/README.md
=> Syntax Error on span function

README.md
=> Minor typo :)

micropython/examples/pico_display/demo.py
Keep the bouncing balls in the court and gives balls a speed in proportion to their size. Created from code in #63
=> Improved bouncing balls demo

drivers/sgp30/README.md, drivers/sgp30/sgp30.cpp, drivers/sgp30/sgp30.hpp, examples/breakout_sgp30/demo.cpp
In a break from previous drivers, I wrote this one from scratch using the Sensirion data sheet. I believe that it captures the useful functions (and the less-than-useful one that measures raw values).
Measurement starts correctly, and readings do seem to vary as you breathe over the sensor! I've compared it with your Raspberry Pi Python library (https://github.com/pimoroni/sgp30-python), and results are consistent (though I did spot a bug in that code - issue raised).
I think I've been consistent in formatting, but please feel free to tidy it if you decide to merge the code. As before, it's based on your breakouts-dev branch.
=> Driver sgp30 Air Quality sensor

micropython/examples/pico_display/thermometer.py
* Display temp as 00.00 with floating point component
* Use the temp value to blend from a list of display colours
* Fixed slowdown bug when screen begins to scroll
=> Improved thermometer demo

.github/workflows/micropython.yml
Tired of this:
Want more this:
=> Append version to MicroPython .uf2

examples/breakout_roundlcd/demo.cpp
=> Fix use of private variable in round LCD demo

.github/workflows/python.yml, micropython/examples/breakout_roundlcd/demo.py, micropython/examples/pico_display/buttons.py, micropython/examples/pico_display/demo.py, micropython/examples/pico_display/rainbow.py, micropython/examples/pico_display/thermometer.py, micropython/examples/pico_explorer/balls_demo.py, micropython/examples/pico_explorer/buttons.py, micropython/examples/pico_explorer/demo.py, micropython/examples/pico_explorer/noise.py, micropython/examples/pico_explorer/rainbow.py, micropython/examples/pico_explorer/thermometer.py, micropython/examples/pico_rgb_keypad/demo.py, micropython/examples/pico_scroll/demo.py, micropython/examples/pico_unicorn/demo.py
This will fail miserably until all the existing examples have been linted :grimacing:
=> Add Python linting

drivers/is31fl3731/is31fl3731.cpp, libraries/breakout_matrix11x7/breakout_matrix11x7.hpp
I missed this one in my haste to get some juicy breakout drivers released!
=> Recover the initialisation patch for is31fl3731

drivers/CMakeLists.txt, drivers/ltr559/CMakeLists.txt, drivers/ltr559/ltr559.cmake, drivers/ltr559/ltr559.cpp, drivers/ltr559/ltr559.hpp, examples/CMakeLists.txt, examples/breakout_ltr559/CMakeLists.txt, examples/breakout_ltr559/demo.cpp, libraries/CMakeLists.txt, libraries/breakout_ltr559/CMakeLists.txt, libraries/breakout_ltr559/breakout_ltr559.cmake, libraries/breakout_ltr559/breakout_ltr559.cpp, libraries/breakout_ltr559/breakout_ltr559.hpp, micropython/examples/breakout_ltr559/demo.py, micropython/modules/breakout_ltr559/breakout_ltr559.c, micropython/modules/breakout_ltr559/breakout_ltr559.cpp, micropython/modules/breakout_ltr559/breakout_ltr559.h, micropython/modules/breakout_ltr559/micropython.cmake, micropython/modules/breakout_ltr559/micropython.mk, micropython/modules/micropython.cmake
Only one example at the moment. May do a PicoExplorer example later today whilst doing trackball.
=> C++ and MP support and example for LTR559 breakout 

micropython/examples/pico_scroll/scroll_text.py
=> Simple example for scrolling text

examples/pico_rgb_keypad/demo.cpp
Rewrites the cursed Pico RGB Keypad code so that it can't hurt anyone else.
Turns out the whole loop could have been a bitwise operator.
The true lesson was the people we met along the way.
Fixes #158
=> Rewrite this code for #158

.github/workflows/micropython-with-blinka.yml, .github/workflows/micropython.yml
Should include fixes and improvements to RP2040 made in versions 6.9.2 and 6.10.1.
=> Bump blinka to 6.10.1 and platformdetect to 3.13.3

.github/workflows/micropython-with-blinka.yml, .github/workflows/micropython.yml, .github/workflows/python.yml, micropython/modules_py/pimoroni.py
Add a pimoroni.py module which includes Python code equivilents of the RGBLED and Button C++ drivers.
This is simpler than binding these drivers into MicroPython and much easier to maintain/extend.
=> Add python module for RGBLED and Button

examples/plasma_2040/CMakeLists.txt, examples/plasma_2040/plasma2040_stacker.cmake, examples/plasma_2040/plasma2040_stacker.cpp
Added a demo for the plasma2040 discussed earlier
=> added staker game demo for plasma2040

micropython/modules/plasma/README.md
Fix documentation around `Button` class's `repeat_time` behaviour.
=> Fix "repeat_time" docs in README

drivers/icp10125/icp10125.cpp
Should fix https://github.com/pimoroni/icp10125-python/issues/2
=> ICP10125: Fix block indefinitely on repeated start

micropython/examples/badger2040/clock.py
...at least on my planet :earth_africa:  :laughing:
=> badger2040: Only 24 hours in a day (not 60)

micropython/examples/pimoroni_pico_lipo/button_blink.py, micropython/modules/badger2040/README.md
Should fix #258 (don't look at how many goes it took me to get that relative link right!)
=> Add Pimoroni Pico LiPo button/LED example, tweak docs

micropython/examples/badger2040/help.py, micropython/examples/badger2040/info.py
=> Badger2040: Add sleep to help and info

micropython/examples/badger2040/conway.py
I made a Conway's game of life simulator for the Badger2040 (as demo'd on [twitter](https://twitter.com/s_j_mcdermott/status/1502331346592714756)). 
I thought it'd be a cool example if you want to include it!
=> Conway's game of life for Badger2040

micropython/examples/badger2040/list.py
Does what it says on the tin!
I added some special handling to clear everything if the list of items was changed at the top of the file, so if a user edits that then they start from scratch.
I also made the update speed slower on page change as a turbo update then leaves the items a bit corrupt.
=> Badger2040: Update list app to use new system

micropython/examples/badger2040/qrgen.py
Signed-off-by: James Sutton <1068763+jpwsutton@users.noreply.github.com>
=> Badger 2040: Support for multiple QR codes.

micropython/examples/badger2040/README.md
Added notes on the change to how the QR Code sample works, and that the Conway sample exists. And some other bits and bobs.
=> Updating the samples README to reflect current contents

.github/workflows/micropython-with-blinka.yml
Blinka -> v7.3.0 for RP2040 i2c pin permutations fix
PlatformDetect -> 3.22.1 for MicroPython fixes
=> Bump Blinka and PlatformDetect for #349

drivers/servo/servo_cluster.cpp
=> Fix for broken asserts in ServoCluster

libraries/bitmap_fonts/bitmap_fonts.cpp
I will probably regret this, but the lack of auto-linebreak on newline was bugging me!
=> Bitmap Fonts: Break to newline on \n.

.github/workflows/micropython-picow.yml
Some notable new commits:
* https://github.com/micropython/micropython/commit/0c45a28d24e1a7f9ea5912c928d7b5a860a6514a
* https://github.com/micropython/micropython/commit/33d6994d4c5855228ae423f2d77fb2549db9f854
=> MicroPython: Bump for macOS USB race cond fix.

.github/workflows/micropython-badger2040.yml
=> BadgerOS: Fix with-modules build.

micropython/modules/jpegdec/jpegdec.cpp
Should fix #490 
(if it works)
Added as a new param to `decode`, use `dither=False` to disable (defaults to enabled):
```python
from picographics import PicoGraphics, DISPLAY_INKY_PACK
import jpegdec
graphics = PicoGraphics(DISPLAY_INKY_PACK)
jpeg = jpegdec.JPEG(graphics)
jpeg.open_file("128.jpeg")
jpeg.decode(0, 0, dither=False)
graphics.set_update_speed(1)
graphics.update()
```
=> JPEGDEC: Add option to disable dither on RGB332.

micropython/examples/inky_frame/image_gallery/README.md
I noticed this link doesn't work and I believe this should fix it.
=> Correct common path

micropython/examples/pico_enviro/enviro_all.py
Now describe_pressure() gives meaningful insights if you set the altitude
Verified it works here:
https://keisan.casio.com/exec/system/1224575267
Verified that it matches the pressure of my iPhone weather app for my location.
If altitude is not set it returns the same value so the altitude variable doesn't need to be edited and it works just as before.
=> Add adjust_to_sea_pressure function

micropython/modules/pico_unicorn/README.md
=> Update Pico Unicorn readme

micropython/examples/galactic_unicorn/clock.py
Unless you're connected to Thonny, the clock will always start from midnight.
This change allows the Galactic Unicorn to connect to wifi and synchronize the time using NTP at boot, and whenever A is pressed to resynchronize.  Time from NTP is UTC, so volume up/down buttons allow the offset in hours from UTC to be set (this is retained over any later NTP synchronization).
=> Add time synchronization from NTP to GU clock example

micropython/examples/galactic_unicorn/feature_test_with_audio.py
Fixes a minor typo, SWITCH_BRIGHTNESS_DOWN text should be Lower not Power.
=> Fix typo galactic_unicorn feature_test_with_audio.py

micropython/examples/badger2040/led.py
This makes a slightly nicer example as the LED goes gently from off to on and back down again instead of strobing.
=> Badger2040: Make the LED example pulse instead of strobe

micropython/examples/galactic_unicorn/README.md, micropython/examples/gfx_pack/calc.py, micropython/examples/plasma_stick/README.md
=> correct sine wave in calc.py

.github/workflows/cmake.yml, .github/workflows/micropython-badger2040.yml, .github/workflows/micropython-picow.yml, .github/workflows/micropython.yml, .github/workflows/python.yml
Just a lot of v2 -> v3.
(Removes a lot of scrolling if you're trying to get a micropython artifact)
=> Update actions for deprecation warnings

micropython/examples/inventor2040w/motors/position_control.py, micropython/examples/inventor2040w/motors/position_on_velocity_control.py, micropython/examples/inventor2040w/motors/tuning/motor_profiler.py, micropython/examples/inventor2040w/motors/tuning/position_on_velocity_tuning.py, micropython/examples/inventor2040w/motors/tuning/position_tuning.py, micropython/examples/inventor2040w/motors/tuning/velocity_tuning.py, micropython/examples/inventor2040w/motors/velocity_control.py
Addresses issue https://github.com/pimoroni/pimoroni-pico/issues/610
=> Fixed typo with inventor examples

README.md
Implement change described here: https://github.com/badges/shields/issues/8671
=> Update CI status badges on README.md

micropython/examples/pico_display/ram_test.py
=> Correct RAM units

README.md, micropython/examples/gfx_pack/README.md, micropython/examples/pico_explorer/README.md, micropython/modules/picographics/README.md
=> Update docs and add links

.github/workflows/cmake.yml, examples/breakout_bme280/bme280_basic.cpp, examples/breakout_bme688/bme688_forced.cpp, examples/breakout_bme688/bme688_parallel.cpp, examples/breakout_bmp280/bmp280_basic.cpp, examples/breakout_dotmatrix/bargraph/bargraph.cpp, examples/breakout_dotmatrix/eyes/eyes.cpp, examples/breakout_dotmatrix/image/image.cpp, examples/breakout_dotmatrix/timer/timer.cpp, examples/breakout_encoder/demo.cpp, examples/breakout_ioexpander/adc/adc.cpp, examples/breakout_ioexpander/button/button.cpp, examples/breakout_ioexpander/servo/servo.cpp, examples/breakout_matrix11x7/demo.cpp, examples/breakout_mics6814/demo.cpp, examples/breakout_potentiometer/demo.cpp, examples/breakout_rtc/demo.cpp, examples/breakout_sgp30/demo.cpp, examples/pico_enc_explorer/pico_enc_explorer.cpp, examples/pico_explorer_encoder/pico_explorer_encoder.cpp, examples/pico_motor_shim/motorshim_motor_song.cpp, examples/pico_pot_explorer/pico_pot_explorer.cpp
Actually run CMake CI for Pico W so we can see what examples are breaking due to making unchecked assumptions about which board they're running on.
=> CI: CMake build for Pico W and Pico.

.github/workflows/micropython-picow.yml
This has been bugging me for a while! It's quite visually noisy.
=> CI: Don't include debug .elf files in artifacts.

libraries/pico_graphics/pico_graphics.cmake
=> PicoGraphics: Include dependencies if necessary.

libraries/galactic_unicorn/galactic_unicorn.cpp, micropython/examples/cosmic_unicorn/melody_maker.py, micropython/examples/cosmic_unicorn/numpy/eighties_super_computer.py, micropython/examples/cosmic_unicorn/numpy/lava_lamp.py, micropython/examples/cosmic_unicorn/numpy/life.py, micropython/examples/cosmic_unicorn/numpy/rgb_channels.py, micropython/examples/galactic_unicorn/numpy/eighties_super_computer.py, micropython/examples/galactic_unicorn/numpy/fire_effect.py, micropython/examples/galactic_unicorn/numpy/lava_lamp.py, micropython/examples/galactic_unicorn/numpy/life.py, micropython/examples/galactic_unicorn/numpy/the_matrix.py, micropython/examples/galactic_unicorn/numpy/this_is_fine.py, micropython/examples/galactic_unicorn/numpy/trippy.py
Works... just a bit faster... 80 FPS instead of 10 FPS.
You can make it 80s again by reducing `PALETTE_ENTRIES` RIIIIGHT down.
=> Cosmic Unicorn: Eighties super computer in numpy/ulab.

micropython/examples/inky_frame/button_demo.py, micropython/examples/inky_frame/inky_frame_daily_activity.py, micropython/examples/inky_frame/inky_frame_news.py, micropython/examples/inky_frame/inky_frame_placekitten.py, micropython/examples/inky_frame/inky_frame_quote_of_the_day.py, micropython/examples/inky_frame/inky_frame_random_joke.py, micropython/examples/inky_frame/inky_frame_xkcd_daily.py, micropython/examples/inky_frame/inkylauncher/main.py, micropython/examples/inky_frame/inkylauncher/nasa_apod.py, micropython/examples/inky_frame/inkylauncher/news_headlines.py, micropython/examples/inky_frame/inkylauncher/random_joke.py, micropython/examples/inky_frame/inkylauncher/secrets.py, micropython/examples/inky_frame/inkylauncher/word_clock.py
- Adds Inky Frame 7.3" support to the Launcher
=> Launcher for Inky Frame 7.3"

.github/workflows/micropython-picow.yml, .github/workflows/micropython.yml
Diff https://github.com/micropython/micropython/compare/05bb26010e4a466a82cfed179f8d8d0b406a78ca...38e7b842c6bc8122753cbf0845eb141f28fbcb72
=> CI: Bump MicroPython to 38e7b84.

.github/workflows/micropython.yml
A crack at #752, since this had bugged me but I didn't have a moment to look into how to fix it.
=> CI: Set MICROPY_GIT_TAG for #752.

micropython/examples/galactic_unicorn/light_sensor.py
Uses the onboard sensor on the unicorn to detect the brightness
Displays the percentage of the brightness value obtained
=>  Added light sensor example with auto brightness feature

micropython/examples/pico_enviro/enviro_all.py
Description generation (eg, humidity -> "good" or "bad") did not match the f-string formatting, which rounds to the nearest value.
=> Enviro Pico description generation did not match f-string rounding

micropython/examples/gfx_pack/README.md, micropython/examples/gfx_pack/carbon_intensity.py
Adds an additional example showing how to use the UK carbon intensity API and display the information on a GFX pack as a sort of bar graph.
Includes documentation in the code and a small update to the relevant README file.
=> Add gfx pack carbon intensity bar graph example.

CMakeLists.txt
=> Fix out of box failure when ARM toolchain is not in path

libraries/pico_vector/pico_vector.cpp
=> Fix newlines in rotated text

.github/workflows/micropython.yml, micropython/micropython_nano_specs.patch, micropython/modules/badger2040/badger2040.cpp, micropython/modules/jpegdec/jpegdec.cpp, micropython/modules/pico_scroll/pico_scroll.cpp, micropython/modules/picographics/picographics.cpp, micropython/modules/pimoroni_i2c/pimoroni_i2c.cpp, micropython/modules/pimoroni_i2c/pimoroni_i2c.h, micropython/modules/pngdec/pngdec.cpp
Raised to surface any build errors we might encounter and provide builds for testing.
:warning: WARNING: This build changes the LittleFS filesystem version, *back up your Python files before updating!* :warning: 
Possible known issues:
* https://github.com/micropython/micropython/issues/13380
* https://github.com/micropython/micropython/issues/13377
=> CI: Bump MicroPython to v1.22.1.

README.md
Our stubs repository is being very well maintained by @North101 and deserves a little more love - https://github.com/pimoroni/pimoroni-pico-stubs
=> README.md: Add link to pimoroni-pico-stubs.

libraries/cosmic_unicorn/cosmic_unicorn.cpp, libraries/galactic_unicorn/galactic_unicorn.cpp, libraries/stellar_unicorn/stellar_unicorn.cpp
Add a comment noting that 256 is the correct maximum brightness.
=> G/S/C Unicorn: Fix get_brightness to use correct max value.

examples/breakout_bme280/bme280_basic.cpp, examples/plasma_stick/plasma_stick_temperature_bme280.cpp
Fixed the bug in the BME280 examples reported in #504
=> Fixed result status bug

examples/breakout_oled_128x128/oled_128x128_demo.cpp
=> Fixed background in SH1107 example

libraries/breakout_rtc/README.md, micropython/modules/breakout_rtc/README.md
New MicroPython & C/C++ Libraries documentation for the RV3028.
Resolves issue highlighted in #207
=> Documentation: RV3028

micropython/modules_py/gfx_pack.md
`Set_pen` command missing from sample code in readme - should help with #971
=> Docs: update GFX Pack readme

micropython/modules/picographics/README.md
Text rotation now works with bitmap fonts :)
=> Picographics: Update README.md

.github/workflows/cmake.yml
This should have been done forever ago!
=> CI: Pin SDK version to 1.5.1.

.github/workflows/cmake.yml, drivers/psram_display/psram_display.hpp, examples/breakout_mlx90640/CMakeLists.txt, examples/breakout_mlx90640/demo.cpp
=> CI: Bump Pico SDK to 2.0.0. 🎉 

.github/workflows/micropython.yml, drivers/uc8151/uc8151.cpp
I don't like having to duplicate these across multiple experimental/feature branches, but it's probably going to turn out that most of these require SDK 2.0.0 / MicroPython > 1.23.x and aren't mergeable yet anyway 😭
=> A roundup of not necessarily related fixes from other branches

libraries/pico_vector/pico_vector.hpp
Fixes inconsistent behaviour due to uninitialized font face.
=> PicoVector: Fully initialise text metrics.

libraries/pico_vector/pretty-poly-primitives.h, libraries/pico_vector/pretty-poly.h
Fixes [this presto issue](https://github.com/pimoroni/presto/issues/41).
=> PicoVector: Fix ppp arc memory corruption.

micropython/examples/stellar_unicorn/stellar_paint/stellar_paint.py
Fixes compatibility issue highlighted by user in issue #1037
=> compatibility changes for use with microdot 2.x

micropython/examples/cosmic_unicorn/cosmic_paint/cosmic_paint.py, micropython/examples/galactic_unicorn/galactic_paint/galactic_paint.py
Updated Cosmic and Galactic examples to match #1061 :)
=> Examples: update Unicorn Paint for microdot 2.x

libraries/pico_vector/pretty-poly.h
Port optimizations from the old version of pretty poly (prior to the C refactor), and a small improvement to `add_line_segment_to_nodes`.
=> PicoVector: Faster polygon rendering.

micropython/modules/picovector/micropython.cmake
I see a 6-7% improvement from this on the vector clock.
=> PicoVector: Set optimization flags.

drivers/vl53l1x/vl53l1x.cpp
Fix a regression introduced in 3e56dfb14c86ee1f77dec212538703742c8cb16a.
=> VL53L1X: bswap registers and values for #1069.
