drivers/msa301/msa301.cmake, drivers/st7789/st7789.cmake, libraries/pico_display/pico_display.cmake, libraries/pico_explorer/pico_explorer.cmake, libraries/pico_explorer/pico_explorer.cpp, libraries/pico_graphics/pico_graphics.cmake, libraries/pico_rgb_keypad/pico_rgb_keypad.cmake, libraries/pico_scroll/pico_scroll.cmake, libraries/pico_unicorn/pico_unicorn.cmake
The added .cmake files can be included into an out-of-tree project whereas - as far as I understand it- CMakeLists.txt is only really for top level config of an CMake build setup. For example here's my CMakeLists.txt for a Pico Explorer project:
```cmake
cmake_minimum_required(VERSION 3.12)
include(pico_sdk_import.cmake)
project(text-pico-explorer C CXX ASM)
set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 17)
pico_sdk_init()
include(../pimoroni-pico/libraries/pico_explorer/pico_explorer.cmake)
add_executable(test-pico-explorer
main.cpp
)
target_link_libraries(test-pico-explorer
pico_explorer)
```
Note the line:
```cmake
include(../pimoroni-pico/libraries/pico_explorer/pico_explorer.cmake)
```
Which pulls pico_explorer and dependencies into our project.
=> Add .cmake files to faciliate out of tree projects

micropython/examples/pico_display/demo.py, setting-up-the-pico-sdk.md
The pico sdk documentation is missing the instructions for creating the PICO_SDK_PATH environment variable which cmake will then fail on later. This CR will add that as well as adds a section explaining how to install the toolchain for macos users.
=> Fixing C++ SDK documentation

examples/pico_display/demo.cpp, examples/pico_explorer/demo.cpp, libraries/pico_graphics/pico_graphics.cpp, libraries/pico_graphics/pico_graphics.hpp, libraries/pico_graphics/types.cpp, micropython/modules/pico_display/pico_display.cpp
Slowly addressing the things raised in #6 
Note: I'm not particularly happy with using `_pen` to avoid shadowing the `pen` type. I guess this is why we used capitalized types in 32Blit.
=> Graphics Enhancements

examples/CMakeLists.txt, examples/pico_unicorn_plasma/CMakeLists.txt, examples/pico_unicorn_plasma/demo.cpp
Added plasma example for Unicorn display based on the Adafruit display example from https://github.com/adafruit/RGB-matrix-Panel/blob/master/examples/plasma_32x32/plasma_32x32.ino
Modified size of plasma blobs and HSV conversion routines to be suitable for the Pico environment. Updated makefiles to build.
Note: It might be worthwhile by default diverting printf to USB as I have here in the other examples
=> Pico Unicorn Plasma

drivers/rv3028/rv3028.cpp, examples/pico_rtc_display/CMakeLists.txt, examples/pico_rtc_display/demo.cpp
Bug in getTimerCount() in driver (was ignoring top byte).
Add auto-repeat on the +/- timer buttons in the example.
Allow PicoExplorer/PicoDisplay selection in the example with #define USE_PICO_EXPLORER 1.
Note that CMakeLists.txt includes the display and explorer libraries, but only one is used.
=> RV3028 driver bug, autorepeat on example buttons

micropython/examples/pico_explorer/demo.py
Added code to show a simple example of the on-board A/B/X/Y button press detection and displaying the result on the display, as this feature of the Pico Explorer hardware was not being demonstrated in the initial demo.py example.
=> Updated demo.py with A/B/X/Y button example

micropython/modules/pico_scroll/README.md
I've added a MicroPython documentation page for the Pico Scroll Pack.  I've tried to keep it in the same style as the Display Pack docs and the docs for the other scroll boards.  Happy to tweak as needed.
=> Added Pico Scroll documentation

drivers/is31fl3731/is31fl3731.cpp, examples/breakout_rgbmatrix5x5/demo.cpp, libraries/breakout_rgbmatrix5x5/breakout_rgbmatrix5x5.cpp, libraries/breakout_rgbmatrix5x5/breakout_rgbmatrix5x5.hpp
Shot in the foot by my compiler, which allowed me to define a broken LED element lookup table like so:
```c++
const RGB lookup_table[] = {
(118, 69, 85),
(117, 68, 101),
(116, 84, 100),
(115, 83, 99),
(114, 82, 98),
(113, 81, 97),
(112, 80, 96),
(134, 21, 37),
(133, 20, 36),
(132, 19, 35),
(131, 18, 34),
(130, 17, 50),
(129, 33, 49),
(128, 32, 48),
(127, 47, 63),
(121, 41, 57),
(122, 25, 58),
(123, 26, 42),
(124, 27, 43),
(125, 28, 44),
(126, 29, 45),
(15, 95, 111),
(8, 89, 105),
(9, 90, 106),
(10, 91, 107),
(11, 92, 108),
(12, 76, 109),
(13, 77, 93),
};
```
The use of `()` instead of `{}` had very quietly broken the lookup table and thus the matrix was not lighting up in any expected pattern.
I've also pulled the init and this lookup mapping out of the example and into the driver, so the …
=> breakouts-dev: Make RGBMatrix5x5 actually work

libraries/pico_graphics/pico_graphics.cpp, micropython/modules/pico_display/usermod.cmake, micropython/modules/pico_explorer/usermod.cmake, micropython/modules/pico_rgb_keypad/usermod.cmake, micropython/modules/pico_scroll/usermod.cmake, micropython/modules/pico_unicorn/usermod.cmake
The upstream MicroPython rp2 port has re-enabled -Werror so we need to either fix warnings or,
in the case of those generated by C++/C MicroPython binding weirdness, suppress them.
=> Fix or suppress warnings

micropython/examples/pico_display/thermometer.py
Keep history for the last 48 (240px / 5px) temperatures readings instead of completely clearing the screen once full.
=> Display thermo example Keep last 48 temperatures

.github/workflows/micropython.yml
USER_C_MODULE support has been merged upstream. Hooray!
=> Switch MicroPython to build against upstream

drivers/st7789/st7789.hpp
Obfuscated by some whitespace changes, the ST7789 `bl` pin default changed from `20` to `21` in https://github.com/pimoroni/pimoroni-pico/commit/f812e23d8e92dda252902c155ac409ab3f154122
=> Revert ST7789 backlight for Pico Display

micropython/modules/pico_rgb_keypad/pico_rgb_keypad.c
Using release 0.1.1 of pimoroni-pico-micropython, the picokeypad.clear() function does not seem to work. Looking through the code, it appears that clear is actually calling init instead. Unfortunately, I'm just starting with micropython and don't have much C experience outside of Arduino, so testing this (or confirming I'm reading the C code for this module correctly) is a bit out of my depth.
=> Fix picokeypad.clear()

setting-up-the-pico-sdk.md
RaspberryPi have updated their build instructions, e.g. the git repo is no longer valid.
=> Update MicroPython build step and reorder it to after toolchain step.

drivers/st7789/st7789.cpp, drivers/st7789/st7789.hpp, examples/breakout_roundlcd/demo.cpp, libraries/breakout_roundlcd/breakout_roundlcd.cpp, libraries/breakout_roundlcd/breakout_roundlcd.hpp
A new constructor has been added which accepts a enum type BG_SPI_SLOT which can be either:
`ST7789::BG_SPI_FRONT` or `ST7789::BG_SPI_BACK`.
This selects the correct CS/BL pins for the respective breakout-garden SPI slot.
Note: the pin designations do not appear to match the BG schematic, but they work!?
This is not a fix for #124 but was for the complexities I observed while looking into it. Took me half an hour to get the darn LCD working even knowing I'd done it before!
Probably needs adding for regular square, too? Not sure how that's all structured.
=> Add breakout-garden SPI slot selection for ST7789 displays

.github/workflows/micropython.yml
This change will require the MicroPython version to be manually bumped with a commit before building a new release of our firmware, but will ensure it's built against a known version of MicroPython.
The release filename now includes the MicroPython version.
=> Fix for MicroPython build changes, and pin to v1.15

.github/workflows/micropython.yml, micropython/modules/breakout_colourlcd160x80/breakout_colourlcd160x80.cpp, micropython/modules/breakout_colourlcd240x240/breakout_colourlcd240x240.cpp, micropython/modules/breakout_trackball/breakout_trackball.cpp
Deliberately renames the pimoroni-pico directory so that paths which reference it will break with a compilation error.
This ensures a micropython build works robustly if a user renames/moves the pimoroni-pico directory relative to micropython.
=> Ensure MicroPython CI breaks with invalid paths

.github/workflows/micropython-with-blinka.yml, .github/workflows/micropython.yml
This new workflow will build a separate release of MicroPython that includes Blinka and PlatformDetect for compatibility with Adafruit CircuitPython .py libraries.
For - mostly - my own convenience both workflow files have been updated to store the .uf2 files as build artifacts, this allows build outputs to be tested without tagging a release but also allows bleeding-edge users to grab pre-release builds.
=> Add a new MicroPython build with PlatformDetect and Blinka as frozen modules

common/pimoroni_i2c.cpp, common/pimoroni_i2c.hpp
This change is specifically intended to avoid a pitfall in MicroPython and will likely have no effect in C++.
When using the REPL in MicroPython it's possible to set up an I2C instance on two pins - ie: 20, 21 - and then subsequently realise these are the wrong pins for your board.
Before this change, these pins would be left hanging even if you created a new I2C instance with new pins - ie: 4, 5 - this would lead to communications failures where they really shouldn't happen. Confusing!
=> Reset unused I2C pins to default when an instance is initialised

drivers/ioexpander/ioexpander.cpp
The pull request fixes the build error from ioexpander when building micropython v1.15.
- OS: Mac OS X 10.15.7
- Compiler: arm-none-eabi-gcc (GNU Arm Embedded Toolchain 10-2020-q4-major) 10.2.1 20201103 (release)
```
[ 56%] Building CXX object CMakeFiles/firmware.dir/Users/davidlin/projects/rp2040/pimoroni-pico/drivers/ioexpander/ioexpander.cpp.obj
/Users/davidlin/projects/rp2040/pimoroni-pico/drivers/ioexpander/ioexpander.cpp In member function 'bool pimoroni::IOExpander::init(bool)':
/Users/davidlin/projects/rp2040/pimoroni-pico/drivers/ioexpander/ioexpander.cpp:337:11: error: 'printf' was not declared in this scope
337 |           printf("Chip ID invalid: %04x expected: %04x\n", chip_id, CHIP_ID);
|           ^~~~~~
/Users/davidlin/projects/rp2040/pimoroni-pico/drivers/ioexpander/ioexpa …
```
=> Fix: Build error from ioexpander.cpp

common/pimoroni_common.hpp, drivers/st7735/st7735.cpp, drivers/st7735/st7735.hpp, drivers/st7789/st7789.hpp, examples/pico_pot_explorer/demo.cpp, libraries/pico_display/pico_display.cpp, libraries/pico_explorer/pico_explorer.cpp
The switch to common I2C and common definitions for SPI had broken an edge case in Pico Explorer where no backlight pin is used.
The backlight pin was inadvertently set to the front Breakout Garden SPI slot default, which is pin 20- this also happens to be the I2C SDA pin for Pico Explorer, breaking I2C comms.
This fix adds a new special case board "PICO_EXPLORER_ONBOARD" so that ST7789 can be initialised without the backlight pin.
This will be useful for anyone using ST7789 without the rest of the Pico Explorer library, although it feels a little contrived.
=> Fix Pico Explorer SPI for #162

micropython/modules/breakout_colourlcd160x80/breakout_colourlcd160x80.cpp, micropython/modules/breakout_colourlcd240x240/breakout_colourlcd240x240.cpp, micropython/modules/breakout_roundlcd/breakout_roundlcd.cpp
x position was being set by y variable so characters only printed in a diagonal line.
=> Fix character positioning for 3 breakout LCD's in Micropython

micropython/examples/pico_wireless/cheerlights.py
As discussed on https://forums.pimoroni.com/t/pico-wireless-pack-fetching-data-from-web/17215/ the cheerlights.py example was stalling on the first HTTP request.
I have added a timeout in this case, so the code will stop waiting and retry after the 60second polling wait period. Users report this does the trick!
=> Retry failed HTTP connections in cheerlights.py

pimoroni_pico_import.cmake
Part of the fix for the Pico Boilerplate breakage mentioned in pimoroni/pico-boilerplate#8
This file is included here for posterity and because it's existence is used to validate PIMORONI_PICO_PATH
=> Add an external import helper module

.github/workflows/micropython-with-blinka.yml, .github/workflows/micropython.yml
* Bump MicroPython from v1.15 to v1.16
* Bump Blinka from 6.10.1 to 6.10.2
* Bump PlatformDetect from 3.13.3 to 3.14.1
* Revert backport patch/hotfix for lwip submodule
Test build: https://github.com/pimoroni/pimoroni-pico/suites/3065698509/artifacts/69808049
Test build with Blinka & PlatformDetect: https://github.com/pimoroni/pimoroni-pico/suites/3065698507/artifacts/69807949
=> Bump MicroPython to v1.16

micropython/modules/breakout_rtc/breakout_rtc.cpp
Permits the range 2000-2099 in the `set_time` method of the RTC Python module, to match the values accepted by the RV3028 driver.
=> Fix RTC year argument for #176

micropython/modules/breakout_colourlcd160x80/breakout_colourlcd160x80.cpp, micropython/modules/breakout_colourlcd240x240/breakout_colourlcd240x240.cpp, micropython/modules/breakout_roundlcd/breakout_roundlcd.cpp
Text code was copied from Display and Explorer, so didn't account for the extra `self` var. Also, Square and Rect LCDs lacked the fix from the Round LCD for non-string vars hardlocking.
=> MP Fix for text scaling on lcd breakouts not working, and non-string vars hard-locking

drivers/ltr559/ltr559.cpp
Proximity LED duty cycle was being passed in as "1.0" intending to select 100%, but this snapped to 25% and skewed the proximity reading.
=> Fix LTR559 duty cycle

drivers/st7789/st7789.cpp
Fixes frame rate/porch register confusion and uses `PWCTRL1` instead of 0xd0. Probably the only thing from my pile of hacks that counts as a fix :smile:
(Also, the `PORCTRL` and `FRCTRL2` values look like the defaults... Maybe a few of the others too, didn't check.)
=> Fix some ST7789 regs

drivers/fatfs/fatfs.cmake, drivers/sdcard/pio_spi.c, drivers/sdcard/pio_spi.h, drivers/sdcard/sdcard.c, drivers/sdcard/sdcard.cmake, drivers/sdcard/sdcard.h, drivers/sdcard/spi.pio
Before this gets lost and neglected on my local filesystem I figured I'd raise a PR.
I don't much like this approach - ie: supplying pins and config via preprocessor defines - but our hands are pretty much tied with how the FatFS library works.
An example config (this is for our pico dv board) might look something like this:
```cmake
target_compile_definitions(raw_images PRIVATE
SDCARD_PIN_SPI0_CS=22
SDCARD_PIN_SPI0_SCK=5
SDCARD_PIN_SPI0_MOSI=18
SDCARD_PIN_SPI0_MISO=19
SDCARD_PIO=pio0
SDCARD_PIO_SM=0
)
```
=> Add support for SD over PIO SPI

.github/workflows/micropython-with-blinka.yml, .github/workflows/micropython.yml
Also rename artefact files so we can tell them apart when downloaded.
=> Bump CircuitPython-compatible MicroPython to 1.16

examples/pico_rgb_keypad/demo.cpp
the ^ operator is a bitwise XOR not OR
=> Correct a typo in pico_rgb_keyboard example

micropython/examples/.gitignore, micropython/examples/pico_wireless/cheerlights.py, micropython/examples/pico_wireless/plasma_ws2812_http.py, micropython/examples/pico_wireless/ppwhttp.py, micropython/examples/pico_wireless/scan_networks.py, micropython/examples/pico_wireless/secrets.py, micropython/modules/pico_wireless/pico_wireless.cpp
Creates a new ppwhttp library to hide the implementation detail of HTTP clients/servers from the examples.
Adds a new example - plasma_ws2812_http.py - showing how to expand rgb_http.py to use a WS2812 pixel strip.
Adds "secrets.py" and moves WIFI connection information there. ppwhttp will throw an error if it's missing.
=> PicoWireless: move HTTP code to ppwhttp library

micropython/modules_py/picosystem.py
Sets up:
* Buttons
* RGB LED
* VBus detect
* Charge detect
* Battery sense
* LCD reset
* Display
TODO: audio :heavy_check_mark: 
TODO: battery sense settings
Crude example to show input, plus VBus and Charge status:
```python
import time
import picosystem
import math
RADIUS = 10
D_PAD_X = picosystem.WIDTH / 4
BUTTONS_X = (picosystem.WIDTH / 4) * 3
ALL_Y = picosystem.HEIGHT / 2
SPACING = (picosystem.WIDTH / 4) - (RADIUS * 2)
BUTTON_POS = (
(BUTTONS_X + SPACING, ALL_Y),
(BUTTONS_X, ALL_Y + SPACING),
(BUTTONS_X, ALL_Y - SPACING),
(BUTTONS_X - SPACING, ALL_Y),
(D_PAD_X, ALL_Y - SPACING),
(D_PAD_X, ALL_Y + SPACING),
(D_PAD_X - SPACING, ALL_Y),
(D_PAD_X + SPACING, ALL_Y),
)
pen_button_pressed = picosystem.display.create_pen(0, 255, 0)
pen_button_released = picosystem.display.create_pen(255, …
```
=> PicoSystem: add helper module to set up PicoSystem

micropython/modules/plasma/README.md
Update the examples using set_led function and replacing to use set_rgb
Fixes #221
=> Fix documentation examples setting RGB LED

drivers/st7789/st7789.hpp, libraries/pico_display_2/pico_display_2.cpp
The ST7789's Tscycw (time between serial write clock cycles) is
16 ns. This can be found on page 44 of the datasheet I'm using:
https://www.waveshare.com/w/upload/a/ae/ST7789_Datasheet.pdf
(I do not know which manufacturer Pimoroni products use and if
their parts might be different. But it seems like this wouldn't
change.)
The existing code sets the SPI baud to 16 * 1000 * 1000. But baud
is Hz, not seconds. That 16 * 1000 * 1000 doesn't represent 16 ns.
It represents 16,000,000 Hz.
16 ns * (1 Hz / s) = 62,500,000 Hz.
This commit changes the baud from 16 * 1000 * 1000 to 62'500'000,
representing ~4x speed improvement in SPI and thus ~4x frame rate
improvement, since the display's frame rate is currently
SPI-limited.
A before & after video can be seen here: …
=> Improve ST7789 frame rate ~4x

micropython/modules/plasma/plasma.c, micropython/modules/plasma/plasma.cpp
There are a few problems with `WS2812.get`:
* The tuple returned contains the types `(int, float, float, float)` instead of `(int, int, int, int)` (which is slightly more efficient and also consistent with the types used by `set_rgb`, and the internal structures); `APA102.get` had the same issue so I fixed that up at the same time.
* The tuple returned simply copies the rgbw fields directly, but in the case of WS2812 (though not APA102) these aren't *necessarily* in the rgbw order (i.e. `set_rgb` corrects for color_order, but `get` doesn't "undo" this correction).
* Finally, the internal implementation is pointing at `APA102.get` (which *really* confused me while working on this as every alteration I made to `WS2812.get` didn't seem to do anything! :)
This commit should fix things up, …
=> Fix ordering of tuple returned by WS2812.get

micropython/examples/breakout_scd41/scd41_demo.py, micropython/modules_py/pimoroni.py
Also adds pins into `pimoroni.py` so they don't need to be repeated in every example. Albeit that's quite handy for making it clear what the pins are.
=> SCD41: Add i2c pins to MicroPython example

.github/workflows/micropython-with-blinka.yml, .github/workflows/micropython.yml, README.md, common/pimoroni_i2c.cpp, common/pimoroni_i2c.hpp, drivers/is31fl3731/is31fl3731.cpp, libraries/pico_explorer/README.md, libraries/pico_rgb_keypad/README.md
* Bump Blinka to 6.20.1 (from 6.14.1)
* Bump PlatformDetetc to 3.19.3 (from 3.15.3)
See MicroPython release notes here: https://github.com/micropython/micropython/releases/tag/v1.18
Grab tests builds from artifacts:
* MicroPython - https://github.com/pimoroni/pimoroni-pico/actions/runs/1745323714
* MicroPython + Blinka - https://github.com/pimoroni/pimoroni-pico/actions/runs/1745323719
Or here:
* MicroPython - [pimoroni-pico--micropython-v1.18.uf2.zip](https://github.com/pimoroni/pimoroni-pico/files/7933561/pimoroni-pico--micropython-v1.18.uf2.zip)
* MicroPython + Blinka - [pimoroni-pico--micropython-v1.18-blinka-6.20.1-platformdetect-3.19.3.uf2.zip](https://github.com/pimoroni/pimoroni-pico/files/7933563/pimoroni-pico--micropython-v1.18-blinka-6.20.1-platformdetect-3.19.3.uf2.zip)
=> Bump MicroPython to v1.18

common/CMakeLists.txt, common/pimoroni_i2c.cmake
So I was trying [the boilerplate project](https://github.com/pimoroni/pico-boilerplate) with the [plasma2040 rotary encoder example](https://github.com/pimoroni/pimoroni-pico/blob/main/examples/plasma2040/plasma2040_rotary.cpp) and it looked like it was trying to link with a library called `pimoroni-i2c` 
There wasn't one, so I made this cmake file to create one, and then could compile the example boilerplate. 
You can check out my boilerplate project [here](https://github.com/lordmortis/pimoroni-plasma-test) - maybe I was setting it up wrong? 
I think the linker is trying to link that library because of [this line](https://github.com/pimoroni/pimoroni-pico/blob/91b3ffb7d81d94009b5ca16ccaf9f0f23d808041/drivers/ioexpander/ioexpander.cmake#L10) in `ioexpander.cmake` ?
=> I2C Library for boilerplate projects?

drivers/st7789/st7789.cpp, micropython/modules/pico_display/pico_display.cpp, micropython/modules/pico_display_2/pico_display_2.cpp, micropython/modules/pico_explorer/pico_explorer.cpp
MicroPython was storing a singleton instance of the Pico Display library pointing to the address of the *first* buffer allocated. Subsequent soft resets would allocate a new buffer in MicroPython but not update the C++  library with its location.
=> Fix display buffer being trampled for #89

.github/workflows/micropython-badger2040.yml, micropython/badger2040_modules_py/boot.py, micropython/examples/badger2040/launcher.py
Attempt to load .py files without the underscore prefix used by their builtin counterparts.
This allows you to override the builtin demos by saving one of the following files on your device:
* `clock.py`
* `fonts.py`
* `ebook.py`
* `image.py`
* `list.py`
* `badge.py`
* `help.py`
* `info.py`
=> Badger2040: Allow builtin demos to be replaced

examples/badger2040/badger2040_image.cpp, examples/badger2040/badger2040_sleep.cpp, libraries/badger2040/badger2040.cpp
Hi,
I'm not sure if you take pull requests, but I've made a couple of fixes to the Badger2040 library to make the C++ examples work correctly.
Main fix is that because `badger.update()` doesn't block, before halting the example should spin waiting for `badger.is_busy()` to return false before powering down, otherwise the last update effectively doesn't happen when running off battery.
The other fixes I've made are to:
- Set pull down on button E, this didn't obviously seem to be causing me a problem but it was odd that it was missing.
- Set the wake button states, as used by the image example (but I don't block waiting for the button to be released)
- Change `update_button_states()` to set the button states to the current value, rather than ORing in pressed buttons to the existing value, …
=> Badger2040 C++ library and example fixes

micropython/examples/badger2040/clock.py
2022 isn't a leap year, so there is no 29th February!
=> badger2040: Set default clock to a valid date

micropython/examples/badger2040/clock.py
(by restricting the maximum number of days in a month as necessary)
The RP2040 datasheet says "The RTC does not check that the programmed values are in range. Illegal values may cause unexpected behaviour."
=> badger2040: prevent date being set to an invalid value

examples/badger2040/image_converter/convert.py, libraries/badger2040/badger2040.cpp, libraries/badger2040/badger2040.hpp
One annoyance with the badger is difference in the behaviour of `halt()` between running with power connected and without.
I realised this would be simple to fix - instead of just looping forever in halt(), instead wait for a button press and then reset - this should give you exactly the same behaviour as when running from battery.
I've also included a couple of other small changes:
- A fix to make convert.py handle images that are already black and white
- And I hope you might indulge me and allow a change from the internal state of the Badger2040 class from private to protected, which would help me continue to use your class as a base for my LowPowerBadger.
=> Make USB powered and battery powered Badger2040 work the same

libraries/badger2040/badger2040.cpp
Fix text rendering at 90, 180 and 270 degree rotations by avoiding float -> int truncation. See #290
=> Badger2040: Fix text rotation aliasing for #290

micropython/examples/badger2040/micropython-builtins.cmake
40 minutes of bashing my head against CMake custom targets and custom commands only to suddenly notice this typo...
:grimacing:
=> Badger2040: Fix builtin module depends typo.

micropython/examples/badger2040/launcher.py, micropython/modules/badger2040/badger2040.c, micropython/modules/badger2040/badger2040.cpp, micropython/modules/badger2040/badger2040.h, micropython/modules/badger2040/badgerinit.S, micropython/modules/badger2040/micropython.cmake
I love the smell of assembler in the morning!  (Well, it was morning when I started).
This change reads the GPIO state and sets the enable 3v3 as early as possible during the boot process.  It shaves a couple of milliseconds off when the buttons are read and the power is enabled, because it's done before the external crystal oscillator is started and stable.
Because the initialization is now done in assembler, I've removed the WakeUpInit class the cpp file, so now there are just trivial functions to read the saved state.
I've also removed the access to pressed_to_wake from the Badger2040 object, as it isn't something apps should be using, and removed clear_pressed_to_wake again as it is unnecessary given the launcher waits for all buttons to be released anyway.
=> Even better Badger wake handling

micropython/examples/badger2040/help.py, micropython/examples/badger2040/info.py, micropython/examples/badger2040/qrgen.py
This fixes #317.  I've also tweaked help to try and improve readability and add the a&c exit combo.  
This has lost the subtlety of USER needing to be pressed after the other buttons on battery, but I'm not sure how clear that was anyway.
One thought I had was that new users are likely to go into an app and have no way of knowing how to exit.  Reset no longer gets you out.  So maybe the default launcher state on a fresh Badger should be to launch the help app?
=> Badger2040: Improve help, info, qrgen

drivers/uc8151/uc8151.cpp, drivers/uc8151/uc8151.hpp, libraries/badger2040/badger2040.cpp, micropython/examples/badger2040/clock.py, micropython/examples/badger2040/conway.py, micropython/examples/badger2040/launcher.py, micropython/modules/badger2040/README.md, micropython/modules/badger2040/badger2040.c, micropython/modules/badger2040/badger2040.cpp, micropython/modules/badger2040/badger2040.h, micropython/modules/badger2040/micropython.cmake
I've added a `badger2040.system_speed()` call to allow the user to easily adjust the clock speed to 5 settings, from 3MHz to 250MHz in sensible steps, applying under/over voltage as appropriate.  Lower clock frequencies are not available when USB is connected, but can be used to save power when on battery.
Clearing the screen and drawing large rectangles were relatively inefficient, so I now do these by editing the framebuffer directly.  Rectangles honour the odd behaviour of being affected by the current thickness setting, to preserve backwards compatibility.
=> Badger2040: system_speed call, plus performance improvements

libraries/badger2040/badger2040.cpp, micropython/modules/badger2040/README.md, micropython/modules/badger2040/badger2040.cpp
Reinitialize UART and SPI after system clock change.
Document that you must change the system clock before initializing any I2C drivers.
=> Reinitialize hardware after system clock change

micropython/modules/breakout_scd41/breakout_scd41.cpp
Attempting to start the SCD41 sensor twice was causing an i2c hardlock for... some reason. This change stops and resets the sensor on "init" to avoid it.
=> Stop & reinit SCD41 to fix lockup for #338

.gitmodules, drivers/vl53l5cx/platform.h, drivers/vl53l5cx/vl53l5cx.hpp, examples/breakout_vl53l5cx/vl53l5cx_demo.cpp, micropython/examples/breakout_vl53l5cx/vl53l5cx_demo.py, micropython/examples/breakout_vl53l5cx/vl53l5cx_motion.py, micropython/examples/breakout_vl53l5cx/vl53l5cx_object_tracking.py, micropython/modules/breakout_vl53l5cx/vl53l5cx.cpp, micropython/modules/micropython.cmake
Saves about 84k, albeit the VL53L5CX library still contains ~1.7k of default configuration values.
The binary must be supplied by the user, but is supplied as "vl53l5cx_firmware.bin". This can be uploaded via Thonny.
The library init becomes:
```python
sensor = breakout_vl53l5cx.VL53L5CX(i2c, firmware=open("vl53l5cx_firmware.bin").read())
```
~~We should probably find a way to hide the implementation detail of loading firmware, since we could better alloc and clean up the 84k of RAM used here rather than using an ephemeral file object and leaving it to GC.~~
=> Sideload vl53l5cx firmware to avoid bloating MicroPython binary

micropython/modules/breakout_as7262/breakout_as7262.cpp, micropython/modules/breakout_bh1745/breakout_bh1745.cpp, micropython/modules/breakout_bme280/breakout_bme280.cpp, micropython/modules/breakout_bme68x/breakout_bme68x.cpp, micropython/modules/breakout_bmp280/breakout_bmp280.cpp, micropython/modules/breakout_dotmatrix/breakout_dotmatrix.cpp, micropython/modules/breakout_encoder/breakout_encoder.cpp, micropython/modules/breakout_icp10125/breakout_icp10125.cpp, micropython/modules/breakout_ioexpander/breakout_ioexpander.cpp, micropython/modules/breakout_ltr559/breakout_ltr559.cpp, micropython/modules/breakout_matrix11x7/breakout_matrix11x7.cpp, micropython/modules/breakout_mics6814/breakout_mics6814.cpp, micropython/modules/breakout_msa301/breakout_msa301.cpp, micropython/modules/breakout_potentiometer/breakout_potentiometer.cpp, micropython/modules/breakout_rgbmatrix5x5/breakout_rgbmatrix5x5.cpp, micropython/modules/breakout_rtc/breakout_rtc.cpp, micropython/modules/breakout_scd41/breakout_scd41.cpp, micropython/modules/breakout_sgp30/breakout_sgp30.cpp, micropython/modules/breakout_trackball/breakout_trackball.cpp, micropython/modules/breakout_vl53l5cx/vl53l5cx.cpp, micropython/modules/pimoroni_i2c/pimoroni_i2c.c, micropython/modules/pimoroni_i2c/pimoroni_i2c.cpp, micropython/modules/pimoroni_i2c/pimoroni_i2c.h
Drops the "finalizer" from "PimoroniI2C". This means I2C pins are not restored to their default states, and I2C is not de-initialized. 
This feels icky, but it's consistent with the behavior of `machine.I2C` which initializes pins and the I2C bus, but does not make any effort to tear them down:
https://github.com/micropython/micropython/blob/1fb01bd6c5dc350f3c617ca8edae8dea9e5516ae/ports/rp2/machine_i2c.c#L110-L118
Can we allocate Pimoroni I2C on the GC_HEAP so the memory used is at least cleaned up? Since with no finalizer "delete" will never be called.
Adds `PimoroniI2C_from_machine_i2c_or_native` which detects the use of `machine.I2C` or `PimoroniI2C` and will upgrade `machine.I2C` to a `PimoroniI2C` instance internally.
Finally I've done some tidyup across all I2C consuming classes, …
=> MicroPython: Make Pimoroni I2C compatible with machine.I2C

micropython/modules/st7789/st7789.cpp
Fix line and triangle primitives.
Rename any "x1, y1" kwargs to just "x, y" if no subsequent coordinates accepted.
Somehow missed these since ST7789 was in progress while #344 was merged.
=> ST7789: Add fixes from #344

pimoroni_pico_import.cmake
Check for pimoroni-pico next to the pico sdk, then next to the project. If neither exist, fail with an error that tells the user to set `PIMORONI_PICO_PATH`.
This is mostly a copy from pico-extras. [Did this while ago... and forgot about it](https://github.com/Daft-Freak/i75-snow-demo/blob/main/pimoroni_pico_import.cmake)
=> Improve PIMORONI_PICO_PATH fallback

examples/pico_display/demo.cpp, examples/pico_display_2/demo.cpp
There's no real reason to pass in a buffer since it's allocated by the class, and since I missed the `round` parameter it was actually setting the displays to round rather than setting a buffer anyway... oof!
Luckily there's no such thing as a round Pico Display!
=> Pico Display & Pico Display 2 Demos: Avoid passing buffer into bool parameter

drivers/as7262/as7262.hpp, drivers/ioexpander/ioexpander.hpp, drivers/ltr559/ltr559.hpp, drivers/msa301/msa301.hpp, drivers/rv3028/rv3028.hpp, drivers/sgp30/sgp30.hpp, drivers/trackball/trackball.hpp, libraries/breakout_encoder/breakout_encoder.hpp, libraries/breakout_mics6814/breakout_mics6814.hpp, libraries/breakout_potentiometer/breakout_potentiometer.hpp
These constructors should never be used. Specifying I2C pins should be done by providing an "I2C" instance.
=> Drop obsolete MicroPython binding compat constructors.

drivers/bme280/bme280.cpp, drivers/bme280/bme280.hpp
I had made a profoundly silly mistake and threw device settings into the ether.
This change correctly sets the settings on the device struct, so BME280 should work!
=> BME280: Correctly set device settings.

.gitignore, micropython/modules/picographics/README.md
I've fixed the typo in the rotation example it had the parameter: 
```python
display = PicoGraphics(display=PICO_DISPLAY, roation=90)
```
which I've fixed with:
```python
display = PicoGraphics(display=PICO_DISPLAY, rotate=90)
```
---
I've also added a bit more information about how to use the sprite sheets after fiddling with that for a bit and then figuring it out.
---
Finally I've added two exclusions to .gitignore:
`.DS_Store` which is some file system cruft that macOS insists on creating in each folder, and also `venv` which is the default folder when creating virtual environments `python -m venv venv`
=> Updated PicoGraphics README and .gitignore

libraries/breakout_mics6814/breakout_mics6814.cpp
As per DrDozzy's comments on Discord, the MICS6814 breakout code uses 'get_raw_red' for both nh3 *and* oxidising readings too, rather than the correct ones.
Note: I don't actually have one of these breakouts, so my testing has been limited to 'does it still compile' :smile:
=> MICS6814: read_nh3 and read_oxidising now call the correct get_raw_* functions

drivers/sh1107/sh1107.cpp, drivers/sh1107/sh1107.hpp, micropython/modules/picographics/picographics.cpp
Add `i2c_address` option to MicroPython PicoGraphics.
=> SH1107: Support for alternate i2c address.

drivers/uc8159/uc8159.cpp, drivers/uc8159/uc8159.hpp
This fixes an issue with setting an `absolute_time_t` (which is a struct with a "private" uint64_t member) to `0`.
=> UC8159: Timeout compiler error fix.

drivers/uc8159/uc8159.cpp, drivers/uc8159/uc8159.hpp, libraries/pico_graphics/pico_graphics.cmake, libraries/pico_graphics/pico_graphics.cpp, libraries/pico_graphics/pico_graphics.hpp, libraries/pico_graphics/pico_graphics_pen_3bit.cpp, libraries/pico_graphics/pico_graphics_pen_p4.cpp, libraries/pico_graphics/pico_graphics_pen_p8.cpp, libraries/pico_graphics/pico_graphics_pen_rgb332.cpp, micropython/modules/jpegdec/jpegdec.cpp, micropython/modules/picographics/micropython.cmake, micropython/modules/picographics/picographics.cpp, micropython/modules/picographics/picographics.h
Add a 3bit pen mode to save 1/4th the RAM needed for the 600x448 Inky Frame.
RAM in MicroPython is still pretty tight, even with this change, so some defensive and memory-aware techniques are required to work with the board.
=> PicoGraphics/UC8159: 3bit bitplane pen mode.

micropython/modules_py/pimoroni.py
Adds a new class to read the buttons on Inky Frame.
Can be read as an 8-bit integer and compared against a bitmask, or treated as an iterable or list to check a specific value.
Note: the bits are shifted out in MSB first (native) bit order so the *nth* bit (0-7) will be the `7-n`th list element.
Usage:
```python
import time
from pimoroni import ShiftRegister
BUTTON_A = 0b00000001
BUTTON_B = 0b00000010
BUTTON_C = 0b00000100
BUTTON_D = 0b00001000
BUTTON_E = 0b00010000
RTC_ALARM = 0b00100000
EXTR_TRIG = 0b01000000
EINK_BUSY = 0b10000000
SR_CLOCK = 8
SR_LATCH = 9
SR_OUT = 10
sr = ShiftRegister(SR_CLOCK, SR_LATCH, SR_OUT)
while True:
result = sr.read()
button_a = sr.is_set(BUTTON_A)
button_b = sr[6]  # Bits come out in MSB-first order
bits = list(sr)
print(result, bits, button_a, button_b) …
```
=> MicroPython: Add ShiftRegister class.

drivers/vl53l5cx/vl53l5cx.hpp, micropython/modules/breakout_vl53l5cx/vl53l5cx.cpp
RAM constrains on Pico W were causing a hardlock. This change allocates the results struct on gc_heap to relieve system RAM pressure.
Fixes #448
=> VL53L5CX: Alloc results data in MPY gc_heap.

.github/workflows/cmake.yml, .github/workflows/micropython-badger2040.yml, .github/workflows/micropython.yml
This change resulted in an incomplete toolchain producing broken, bloated builds with exceptions and introspection enabled.
=> CI: Revert: wget ARM GCC toolchain

micropython/modules/pcf85063a/pcf85063a.c, micropython/modules/pcf85063a/pcf85063a.cpp, micropython/modules/pcf85063a/pcf85063a.h
PCF has a free byte that can be written to and read from. Useful for storing state information separate from the main processor.
=> Exposed byte access for PCF RTC

drivers/st7789/st7789.hpp
When I tried to overclock my Tufty the display went odd (it actually split in two taking up the top half of the screen - seems the display hardware copes OK with the clock being two fast - it just misses every other byte, or something like that).
This PR makes PIO setup take account of the current system clock when specifying the divider.  Using a maximum of 32MHz is a fairly conservative guess at where the safe limit is - my Tufty works OK at 40MHz.  The old default was 31.25MHz if you kept a 125MHz system clock.
=> ST7789 Parallel: Work with SYS clock faster than default

micropython/examples/pico_explorer/button_test.py, micropython/examples/pico_explorer/demo.py, micropython/examples/pico_lipo_shim/battery_pico.py, micropython/examples/pimoroni_pico_lipo/battery_pico_display.py, micropython/examples/pimoroni_pico_lipo/battery_pico_explorer.py, micropython/modules/pico_explorer/README.md
The constants in the `picoexplorer` module were available in the Pico build but not the Pico W build, which was causing confusion. 
Removed remaining references to the old picoexplorer module and updated docs and examples to use pin numbers instead of constants (which makes more sense for Explorer, as it has a handy pin number reference on the bottom of the board). I guess `picoexplorer` can now be removed from all builds!
I've also updated a few display examples that escaped my last rush of Picographics updates.
Fixes #499
=> Remove `picoexplorer` references

examples/inky_pack/inky_pack_demo.cpp
I am using the inky pack. When setting the pen to 1 to write text against a black background (pen = 0), the text is not legible.  Setting it to 15 (white) is much more legible and serves as a much better demo.
=> set pen for text to 15 for better visibility

drivers/st7735/st7735.cpp, drivers/st7789/st7789.cpp, drivers/st7789/st7789.hpp, drivers/uc8159/uc8159.cpp, libraries/pico_graphics/pico_graphics.cpp, libraries/pico_graphics/pico_graphics.hpp, libraries/pico_graphics/pico_graphics_pen_3bit.cpp, libraries/pico_graphics/pico_graphics_pen_p4.cpp, libraries/pico_graphics/pico_graphics_pen_p8.cpp, libraries/pico_graphics/pico_graphics_pen_rgb332.cpp
This fixes an issue where the Tufty display was mildly corrupted when using Pico Graphics modes other than RGB565.
The problem was the DMA transfer in ST7789 would read from the same buffer that the scanline conversion was setting up for the next line.  This meant that the first few pixels of each row would have the values from the next row, and could possibly cause further corruption if the RP2040 was otherwise busy (e.g. when USB is enabled).
=> Pico Graphics: Double buffer scanline conversion

libraries/pico_graphics/pico_graphics.cpp, libraries/pico_graphics/pico_graphics_pen_p4.cpp
The 4-bit paletted pen mode was using *only* the `x` coordinate of a pixel to determine which nibble to set. This resulted in the wrong nibble being set for displays with an uneven width. EG: Pico Display is 135x240 in portrait. See #422 for an example.
=> PicoGraphics: Fix a bug that broke #422

micropython/examples/tufty2040/pride_badge.py
This adds the chevrons on the left of the flag from the [Progress Pride](https://www.vam.ac.uk/articles/the-progress-pride-flag) Flag to the pride badge.
The chevron colours are defined in the `CHEVRONS` array - no chevrons can be displayed by making the array zero length.
The height of the initial chevron is defined by `FIRST_CHEVRON_HEIGHT`; the width of the remaining chevrons are automatically calculated.
=> Add Progress Pride flag to pride badge example.

micropython/modules/plasma/README.md
Documentation for set_brightness function was under WS2812 but text referred to APA102, and set_brightness is not supported on WS2812. I've moved the paragraph to the end of the APA102, verbatim.
=> Move set_brightness to APA102

micropython/modules/plasma/plasma.cpp
When no buffer was supplied it would fall upon the class to call "new" and allocate within C/C++'s (very small) heap.
Ensure a MicroPython managed buffer (allocated from gc_heap) is always supplied to the APA102/WS2812 classes.
=> Plasma: Use m_new to alloc buffer on gc_heap if not supplied.

examples/plasma_stick/plasma_stick_alternating_blinkies.cpp, examples/plasma_stick/plasma_stick_encoder.cpp, examples/plasma_stick/plasma_stick_fire.cpp, examples/plasma_stick/plasma_stick_rainbows.cpp, examples/plasma_stick/plasma_stick_temperature_bme280.cpp
Skully kit uses RGB rather than GRB LEDs, so made examples like fire.py show as green.
=> Switched the Plasma Stick colour order and fixed BME280 example

micropython/examples/galactic_unicorn/clock.py, micropython/examples/galactic_unicorn/scrolling_text.py
=> More Galactic Unicorn Examples

drivers/ltp305/ltp305.cpp
The birghtness setting on the LTP305 driver didn't work because the local variable hid the member variable.
=> Fix setting the LTP305 brightness

libraries/jpegdec/JPEGDEC.cpp, libraries/jpegdec/JPEGDEC.h, libraries/jpegdec/jpeg.inl, micropython/modules/jpegdec/jpegdec.cpp
Fixes https://github.com/pimoroni/pimoroni-pico/issues/573
=> JPEGDEC/PicoGraphics: Add support for RGB888 target.

libraries/galactic_unicorn/galactic_unicorn.cpp, libraries/pico_synth/pico_synth.hpp
In reference to [#595](https://github.com/pimoroni/pimoroni-pico/issues/595), this makes the volume in PicoSynth changeable, and then reflects the volume setting in the GalacticUnicorn library into that.
side question: should there be a distinct `volume` within GalacticUnicorn at all, or should it just fully reflect PicoSynth? I've taken the approach of touching the bare minimum, but it could be done more thoroughly if desired...
I *think* that volume is currently only `const` because the bulk of the logic has been borrowed from the 32blit synth stuff, which has an externally set volume (via the firmware) but if I'm wrong and there's a really good reason for it, feel free to torpedo this PR :smiley_cat:
=> Unicorn volume fix

micropython/examples/badger2040/README.md
Using 108 resulted in a 'smeared' image because the image width is wrong for the result.  Check the [getting started guide](https://learn.pimoroni.com/article/getting-started-with-badger-2040) where it says 104x128 for badge picture
=> Correct badge picture dimensions

pimoroni_pico_import.cmake
When `$PIMORONI_PICO_FETCH_FROM_GIT` environment variable is set
cmake script will fetch on the go git repository and use it to
build your project.
User can additionally use `$PIMORONI_PICO_FETCH_FROM_GIT_PATH` to
specify target directory for source code of fetched SDK.
This patch was inspired by [external/pico_sdk_import.cmake](https://github.com/raspberrypi/pico-sdk/blob/master/external/pico_sdk_import.cmake) from
official C/C++ [pico-sdk repository](https://github.com/raspberrypi/pico-sdk).
=> Fetch pimoroni-pico SDK from git repository

micropython/examples/inky_frame/inkylauncher/main.py
Increased the delay to give the USB a little longer to initialise on startup.
=> usb-fix for Inky Frame Launcher

libraries/galactic_unicorn/galactic_unicorn.cpp
Enables support for PEN_RGB332 on the Galactic Unicorn; this is necessary to support the sprite functions of PicoGraphics, which only work with that pen.
(This replaces https://github.com/pimoroni/pimoroni-pico/pull/616 with a single commit PR that doesn't mess up random other line endings too, after I made a *real* mess of that original branch trying to make it better - sorry!)
=> Added PEN_RGB332 support

libraries/galactic_unicorn/galactic_unicorn.cpp, libraries/galactic_unicorn/galactic_unicorn.pio
Select the row before streaming out the pixel data, as the row change takes a few cycles to propagate.
=> Fix ghosting on the Galactic Unicorn

micropython/examples/tufty2040/main.py
Primarily motivated to get almost everything out of globals and fix issue #631. This is a stripped-down version of the gist there without the memory debugging and reboot-into-direct-boot mode.
Mostly move things to functions. Clean up some dead code and comments. I think the biggest win is not actually the PicoGraphics framebuffer, which is well-behaved, but random temporary floats that were leaking previously.
Also type-annotated and lints clean.
Fixes #631. (As much as I think is possible.)
=> Rewrite the Tufty2040 main menu somewhat

micropython/modules/badger2040w/README.md
When installing the alternative firmware I saw the notice at the top of the README that the "badger2040w.py" and "network_manager.py" files need to be downloaded separately. After adding these two scrips to the Badgerw it gave `ImportError: no module named 'WIFI_CONFIG'`. This was not something that the README said was required. Therefore my PR adds the "WIFI_CONFIG.py" to the top README file.
=> Update to Badger 2040 W getting started

micropython/modules/badger2040w/README.md
Looks like someone forgot to update the function names in the Badgerw's readme (they were still the ones from the old library).
=> Update function names in readme

micropython/examples/cosmic_unicorn/launch/today.py
Errors caused by the user not having a secrets.py file on their device have now been fixed. The date will revert to the Pico RTC when no network is available.
=> Patch: fixed error caused by missing secrets.py

micropython/examples/badger2040/qrgen.py
Hello!
I'm planning on taking my Badger2040 to an event soon and in doing so, needed to update the QR codes that were available for display in qrgen.py. In setting up the new files, I ended up with one fewer file than I had previously uploaded and so when trying to display the QR codes from the launcher, instead of seeing the first QR code, I received a warning saying "List index out of range".
After some debugging, I discovered that this was because the state/qrcodes.json file had remembered the last QR code viewed and that the index of this was now higher than the count of text files in the qrcodes folder.
Commit [eb7eaae](https://github.com/pimoroni/pimoroni-pico/commit/eb7eaae88532d29cb392947ff464544b39899841) loads the state, checks to see if the last viewed index is in range and if …
=> List index out of range fix, remove default QR message if text files are available and file housekeeping

examples/interstate75/interstate75_rainbow.cpp, examples/pico_display_2/pico_display_2_demo.cpp, examples/pico_enc_explorer/pico_enc_explorer.cpp, examples/pico_pot_explorer/pico_pot_explorer.cpp, examples/pico_unicorn/demo.cpp, examples/tufty2040/tufty2040_drawing.cpp, libraries/pico_graphics/pico_graphics.cpp, libraries/pico_graphics/pico_graphics.hpp, libraries/pico_graphics/pico_graphics_pen_3bit.cpp, libraries/pico_graphics/pico_graphics_pen_inky7.cpp, libraries/pico_graphics/pico_graphics_pen_p4.cpp, libraries/pico_graphics/pico_graphics_pen_p8.cpp, libraries/pico_graphics/pico_graphics_pen_rgb332.cpp, libraries/pico_graphics/pico_graphics_pen_rgb565.cpp, libraries/pico_graphics/pico_graphics_pen_rgb888.cpp
`create_pen` returns an int with the most significant byte set to indicate it is an RGB888 colour.
Pen values without the most significant byte set are treated as palette entries and handled normally.
=> Inky 7.3: Support dithering of arbitrary colours.

.github/workflows/cmake.yml
Try to fix the LONG CMake compile for Pico W mentioned in #642
Note: It's expected that this will probably *not* speed up the first time it's run... so poke this PR when it finishes.
=> CI: Separate CCache cache for Pico/PicoW.

micropython/examples/tufty2040/autobright.py
Standalone smoothed display auto-brightness, reactive to the on-board LUX and battery ADC sensors, with debugging keys so it's easier to test (and play with).
Closes pull requests #628 and #629, which did this to the retro_badge example, but made it too complicated.
=> Contribute an automatic display brightness example

micropython/modules/micropython-common.cmake, micropython/modules/micropython-picow_inky_frame.cmake, micropython/modules/micropython-tufty2040.cmake, micropython/modules/test.cmake, micropython/modules_py/modules_py.cmake
* Feature parity between Badger 2040 and Tufty 2040.
* Add ulab to Tufty 2040.
* Don't include modules_py modules for boards that don't use/need them.
* Tweak modules_py.cmake so modules can be copied by parent CMake files.
* Simplify copy_module function to avoid repetition.
=> MicroPython: Tidy up CMake files for our boards.

micropython/examples/cosmic_unicorn/clock.py, micropython/examples/galactic_unicorn/clock.py, micropython/examples/interstate75/75W/clock.py
Use a modulo to constrain the displayed hour to 0 - 24 after applying the UTC offset.
Very small change to the Galactic Unicorn, Cosmic Unicorn, and Interstate75 `clock.py` examples.
=> clock.py: constrain hour to 0 to 24

micropython/modules/badger2040-micropython.cmake, micropython/modules/cppmem/cppmem.c, micropython/modules/cppmem/cppmem.cpp, micropython/modules/cppmem/cppmem.h, micropython/modules/cppmem/micropython.cmake, micropython/modules/micropython-badger2040w.cmake, micropython/modules/micropython-common.cmake, micropython/modules/micropython-pico.cmake, micropython/modules/micropython-picolipo_16mb.cmake, micropython/modules/micropython-picolipo_4mb.cmake, micropython/modules/micropython-picow.cmake, micropython/modules/micropython-picow_cosmic_unicorn.cmake, micropython/modules/micropython-picow_enviro.cmake, micropython/modules/micropython-picow_galactic_unicorn.cmake, micropython/modules/micropython-picow_inky_frame.cmake, micropython/modules/micropython-tiny2040.cmake, micropython/modules/micropython-tufty2040.cmake, micropython/modules_py/boot.py
This is more a test to see if I'm barking up the right tree than a fix... yet.
=> MicroPython: Magic C++ Memory Management.

.github/workflows/micropython.yml
Caused build errors in PRs that didn't even touch the C++ code or CMake tooling, eg:
https://github.com/pimoroni/pimoroni-pico/pull/751
https://github.com/pimoroni/pimoroni-pico/pull/754
=> CI: Fix various build errors due to a caching race condition.

micropython/modules_py/inky_frame.md
It also seems to have changed the last line in the file - I guess it's added a carriage return or something similar.
=> Fix relative link to PicoGraphics documentation

micropython/modules_py/inky_frame.py
Expanded `sleep_for()` function to allow for sleeps longer than 24 hours - by adding the day component to the alarm, this maximum can be stretched to a month (capped at 28 days)
I've validated the code as best I can, but I don't actually possess an Inky Frame myself :-)
ref: https://github.com/pimoroni/pimoroni-pico/issues/744
=> Inky Frame: longer sleep_for

drivers/ltp305/ltp305.cpp, drivers/vl53l1x/vl53l1x.cpp, libraries/hershey_fonts/hershey_fonts.hpp
These fixes were required to make the current `main` branch compile on macOS 13.3.1 using `arm-none-eabi-gcc @13.1.0` from MacPorts.
=> Fixes for compilation under macOS / GCC 13.3.1

libraries/cosmic_unicorn/cosmic_unicorn.cpp, libraries/cosmic_unicorn/cosmic_unicorn.pio
This is applying the same ghosting fix as for Galactic to Cosmic.  I've just given it a brief test and it seems to be working.
The change is to apply the row selection earlier, as it appears to take a few cycles to propagate so the previous method of changing it immediately before display starts very briefly lights the previous row.
=> Ghosting fix for Cosmic

drivers/st7789/st7789.cpp
Use DMA to transfer the display buffer to PIO rather than pushing into the TX FIFO in a loop.
Co-authored by @zx64 - https://github.com/pimoroni/pimoroni-pico/issues/776
=> Tufty 2040: DMA display update.

.github/workflows/micropython.yml
This formalises a sort of cache-buster we can bump if the workflow changes significantly. This ensures the cache key remains consistent between the dependency and individual jobs so we don't get a race condition where a dirty cache will break subsequent builds.
The hacks to revert Pico SDK / MicroPython to its vanilla state have been removed, too, since this *should* be guaranteed by the (hopefully now clean) cache.
=> CI: Add workflow version to cache key.

.github/workflows/micropython.yml, micropython/board/PICO_W/board.json, micropython/board/PICO_W/manifest.py, micropython/board/PICO_W/mpconfigboard.cmake, micropython/board/PICO_W_ENVIRO/board.json, micropython/board/PICO_W_ENVIRO/manifest.py, micropython/board/PICO_W_ENVIRO/mpconfigboard.cmake, micropython/board/PICO_W_ENVIRO/pico_sdk.patch, micropython/board/PICO_W_INKY/board.json, micropython/board/PICO_W_INKY/manifest.py, micropython/board/PICO_W_INKY/mpconfigboard.cmake, micropython/board/PICO_W_INKY/pico_sdk.patch
Bluetooth support for Pico W, Inky and Enviro builds.
=> MicroPython: Pico W Bluetooth Support

micropython/modules/picographics/picographics.cpp
This is a little bit experimental, but along with some Python tooling to help people get font data in the right shape this might make bitmap fonts actually nice and useful while we figure out vector ones!
=> PicoGraphics: Add MicroPython support for custom font data.

micropython/modules/picographics/README.md
(VSCode also stubbornly fixed some trailing space.)
Closes #765.
=> Document PicoGraphics fixed_width

micropython/examples/pico_unicorn/demo-picographics.py, micropython/examples/pico_unicorn/rainbow-picographics.py, micropython/examples/pico_unicorn/vertical-fire.py, micropython/modules/picographics/README.md
As mentioned on the [forum](https://forums.pimoroni.com/t/pico-unicorn-pico-graphics/22811/4), the examples for the Pico Unicorn Pack used the 'native' graphics, rather than the newer PicoGraphics based ones.
Duplicated the two existing examples into `-picographics` versions, and added a version of `fire-effect.py` from the other Unicorns' examples, turned on it's side to get a bit more height displayed!
Also updated the PicoGraphics readme to (a) acknowledge the existence of the Pico Unicorn, and (b) mention that the special `update()` handling applies to *all* Unicorns, not just the Galactic.
=> Added some PicoGraphics based MP examples for the PicoUnicorn

drivers/encoder/encoder.cpp, drivers/hub75/hub75.hpp, drivers/hub75_legacy/hub75.hpp, drivers/plasma/apa102.hpp, drivers/plasma/ws2812.hpp, drivers/pwm/pwm_cluster.cpp, drivers/sdcard/pio_spi.h, drivers/st7789/st7789.hpp, examples/pico_explorer_encoder/pico_explorer_encoder.cpp, libraries/cosmic_unicorn/cosmic_unicorn.cpp, libraries/galactic_unicorn/galactic_unicorn.cpp, libraries/pico_unicorn/pico_unicorn.cpp, libraries/stellar_unicorn/stellar_unicorn.cpp
I had trouble with my local MicroPython build for ages until @Daft-Freak suggested wrapping the `pio.h` includes like this..  I feel this should be in the standard build to avoid others having the same pain!
=> Fix clean Micropython build

libraries/pico_graphics/pico_graphics.hpp, libraries/pico_vector/pico_vector.hpp
This is just a hook to allow the pen implementation to provide a fast alpha blend for a picovector tile.
=> Allow pen function for fast tile alpha blending

libraries/pico_vector/alright_fonts.cpp, libraries/pico_vector/alright_fonts.hpp, libraries/pico_vector/pico_vector.cmake, libraries/pico_vector/pico_vector.cpp, libraries/pico_vector/pretty_poly.cpp, libraries/pico_vector/pretty_poly.hpp, libraries/pico_vector/pretty_poly_types.hpp, micropython/modules/picovector/micropython.cmake
While looking at the performance of the alpha blend, I noticed there were lots of blank rows.  This led me to suspect there would be some easy wins in the polygon rendering side of things.
Main change is to track the actually used tile bounds in render_nodes so the graphics callback only renders the used part of the tile (and indeed only if it is used at all).  Potentially this could be done more efficiently earlier, but this way is relatively simple.
Additionally I fixed up the todo in `add_line_segment_to_nodes` so it's not running through out of bounds rows.
=> Improve pretty_poly performance

micropython/examples/inky_frame/inkylauncher/nasa_apod.py, micropython/examples/inky_frame/inkylauncher/news_headlines.py
This very small PR accomplishes two things:
1. Swaps the protocol from `http` to `https` for BBC's example rss feeds. The current feed requests were failing because BBC has implemented a redirect on RSS to enforce `https`.
2. Adds a comment for the 7.3 frame size, to match the existing ones for the other Inky Frame sizes.
=> [Inky Frame] Fix news headline redirect example

micropython/examples/plasma_stick/README.md
Add link to other resources section for [Plasma LEDs](https://github.com/bitcdr/plasma-leds).
Control LEDs attached to a [Pimoroni Plasma Stick 2040 W](https://shop.pimoroni.com/products/plasma-stick-2040-w) with your web browser.
The Plasma LEDs features a clean web frontend, which allows you to control the LEDs attached to a [Pimoroni Plasma Stick 2040 W](https://shop.pimoroni.com/products/plasma-stick-2040-w) via a web browser.
It comes with a variety of configurable colors and effects out of the box, and is extendable to additional effects if you have the programming skills.
Some of the effects are based on the awesome [example code provided by Pimoroni](https://github.com/pimoroni/pimoroni-pico/tree/main/micropython/examples/plasma_stick).
=> [Plasma Stick 2040W] add Plasma LEDs link

examples/plasma_stick/plasma_stick_rainbows.cpp, micropython/examples/plasma_stick/rainbows.py
In this example the use of the monotonically increasing `offset` variable in the hue calculations will cause the colours to stop rotating when the repeated addition of 20 / 2000 eventually becomes too small to make a difference to the accumulated value given the limited precision of a `float`.    That is, at some point `offset += float(SPEED) / 2000.0f` becomes a no-op.
<strike>Granted it will take a long time - 265 days with the current code - but in a modified version of this demo I've been able to trigger issues far more rapidly.</strike>
This patch first makes sure that `offset` doesn't increase without bound so that it stays within the numerical precision range of a `float`, and secondly ensures that all hue values passed to `RGBLED::set_hsv()` are within the range [0..1)
The second …
=> fix hue errors in plasma_stick_rainbows

micropython/examples/interstate75/75W/clock.py
Previously, if we dropped out of the wlan loop early because of an error (wlan.status() < 0) it would still print "Connected", and try to set the time.
=> fix: Only set time if the wlan is connected

micropython/modules/pico_scroll/README.md
Addresses/fixes #861
I can't get the functions that involve bytearrays to do anything though - are these defunct with PicoGraphics?
=> update picoscroll docs

micropython/examples/inky_frame/inky_frame_rtc_demo.py
This adds a really primitive adjustment for time zones. The user can simply set the value for `tz_offset` to the hours difference to UTC and it will do a really simple calculation. This isn't real time zone support, but it lets a new user at least see this demo in their current time zone.
=> add adjustment for time zone offset

.github/workflows/micropython.yml, ci/micropython.sh, micropython/board/pico-sdk-patch.sh, micropython/micropython_nano_specs.patch, micropython/modules/badger2040/badger2040.cpp, micropython/modules/jpegdec/jpegdec.cpp, micropython/modules/pico_scroll/pico_scroll.cpp, micropython/modules/picographics/picographics.cpp, micropython/modules/pimoroni_i2c/pimoroni_i2c.cpp, micropython/modules/pimoroni_i2c/pimoroni_i2c.h, micropython/modules/pngdec/pngdec.cpp, micropython/modules_py/modules_py.cmake
For a few reasons:
1. Reduce our dependency on GitHub actions workflows
2. Attempt to provide tools we can run locally to replicate a CI build
3. Make build steps more discoverable and less intertwined with GitHub Actions idiosyncrasies
This changeset also switches to `arm-none-eabi-gcc-action` (instead of apt) to handle installing the ARM GCC toolchain. This uses caching, speeding up the compiler install from 60+ seconds down to about 7 seconds.
I have dropped our "deps" step (a pre-requisite of each MicroPython build) in favour of just setting up the environment for each build. This is - in theory - slower, but is much less complicated and less prone to weird errors.
=> CI: Move some workflow steps into ci/micropython.sh

drivers/st7789/st7789.cpp
This should, in theory, fix the weird display corruption bug affecting Tufty 2040.
=> st7789: Remove mystery meat command implicated by #567.

libraries/motor2040/motor2040.hpp, libraries/servo2040/servo2040.hpp
Add definitions for the QW/ST connector SDA & SCL pins
addresses #889
=> Add I2C pin definitions to motor2040 header

libraries/pico_graphics/pico_graphics_pen_1bitY.cpp, micropython/modules/pngdec/pngdec.cpp
These fixes are required for PNGDEC to function correctly on Badger 2040 and Badger 2040 W, so it can be added - https://github.com/pimoroni/badger2040/pull/75
The fix to `PicoGraphics_Pen1BitY::set_pen` corrects handling of RGB and ARGB PNGs.
The fix to PNGDEC adds explicit support for 1bit PNGs, which would obviously be desirable on a 1bit display.
=> Fixes for PNGDEC on Badger 2040 / Badger 2040 W

.github/workflows/micropython.yml, drivers/hub75/hub75.cpp, drivers/hub75/hub75.hpp
This patch release includes a number of fixes for RP2, notably:
* rp2/rp2_dma: fix fetching 'write' buffers for writing not reading
* rp2/machine_uart: fix event wait in uart.flush() and uart.read()
* rp2: change machine.I2S and rp2.DMA to use shared DMA IRQ handlers
https://github.com/micropython/micropython/releases/tag/v1.22.2
* https://github.com/pimoroni/pimoroni-pico/pull/899
* https://github.com/pimoroni/pimoroni-pico/pull/907
=> CI: Bump MicroPython to v1.22.2.

micropython/modules/pngdec/pngdec.c, micropython/modules/pngdec/pngdec.cpp
Special case 1bit PNGs to use fixed black/white values or optionally - with MODE_PEN - draw the PNG in the current pen colour.
=> PNGdec: Add greyscale support.

micropython/modules/pngdec/pngdec.cpp
As if PNG rendering isn't already complex enough, I dreamed up "palette_offset" as an argument that would change a "COPY" mode PNG's pixel value by a certain offset value.
Eg: if you have a 4bit (16 colour) greyscale or indexed PNG you could copy it verbatim into the PicoGraphics buffer (ignoring the actual colour values). Normally this happens from palette index 0, so you could never swap out the palette to handle artwork variations.
Using an offset, - eg let's say we offset by 16- it's possible to render a PNG in "COPY" mode, offsetting each palette index by 16. Now in 8-bit palette mode we can draw up to sixteen copies of our PNG and - via palette manipulation - give them all distinct colours.
Yes, even trying to explain this is complicated...
=> PNGdec: Add support for palette offsets and greyscale copy mode

drivers/inky73/inky73.cpp, drivers/inky73/inky73.hpp
Add a timeout to fix Inky 7.3" hanging on batteries.
Basically assumes the update has finished if it takes > 45s, and allows a subsequent attempt rather than hanging indefinitely.
Raised, tested and fixed by w3stbam: https://github.com/pimoroni/pimoroni-pico/pull/900
Rewritten as mentioned in the PR.
Replaces #900
=> inky73: Add busy wait timeout.

drivers/st7789/st7789.cpp
Test script, modified from the repro provided in #562 -
```python
from picographics import PicoGraphics, DISPLAY_PICO_DISPLAY, PEN_P4
import time
def draw_outline(rotate):
display = PicoGraphics(display=DISPLAY_PICO_DISPLAY, pen_type=PEN_P4, rotate=rotate)
W, H = display.get_bounds()
MIN_X = 0
MIN_Y = 0
MAX_X = W - 1
MAX_Y = H - 1
print(W, H)
RED = display.create_pen(255, 0, 0)
GREEN = display.create_pen(0, 255, 0)
BLUE = display.create_pen(0, 0, 255)
WHITE = display.create_pen(255, 255, 255)
BLACK = display.create_pen(0, 0, 0)
colours = [RED, GREEN, BLUE, WHITE]
display.set_pen(BLACK)
display.clear()
display.set_pen(colours[rotate // 90])
display.line(MIN_X, MIN_Y, MAX_X, MIN_Y)
display.line(MAX_X, MIN_Y, MAX_X, MAX_Y)
display.line(MAX_X, MAX_Y, MIN_X, MAX_Y)
display.line(MIN_X, MAX_Y, …
```
=> PicoDisplay: Fix misalignment on rotated Pico Displays (fixes #562.)

.github/workflows/micropython.yml
This is a replacement to #927 with the intention of catching issues where the MicroPython binary leaks into the LittleFS filesystem region.
Since this PR involves no changes to the MicroPython codebase and requires no linker script modifications or other tomfoolery, it should be much easier to maintain for, more or less, the same result.
=> CI: Add py_decl verify step to catch binary overflows.

micropython/modules/picographics/README.md
I added a subsection for PNG File support in Pico Graphics by copying and adapting the text from these release notes - https://github.com/pimoroni/pimoroni-pico/releases/tag/v1.20.4 - about the PNGdec functionality.
=> Add PNG File subsection to Pico Graphics documentation

micropython/examples/inky_frame/inkylauncher/news_headlines.py
- Applied the fixes from [here](https://github.com/pimoroni/picovision/pull/97) to news headline example.
- `get_rss()` now returns an empty list on failure rather than False.
=> Patch inky launcher

libraries/breakout_mics6814/breakout_mics6814.hpp
As raised in #618.
Confirmed correct pins as shown in the schematic [here](https://cdn.shopify.com/s/files/1/0174/1800/files/MICS6814_breakout_schematic.pdf?v=1628772412)
=> Corrected pin definitions for OX and RED

examples/tufty2040/tufty2040_drawing.cpp
Updated button example code so the polarity is correct and returns true when the buttons are pressed. As raised in #505
=> Fixed button polarity

.github/workflows/micropython.yml, setting-up-micropython.md
When I go to fetch an artifact for a MicroPython build my brain is always confounded by the repetition of "pimoroni-" before each file.
Change the names so the product is up-front, so the list is easier to scan-read through.
This will break: https://github.com/pimoroni/pimoroni-pico/blob/main/setting-up-micropython.md (TODO: fix in this PR)
And probably: https://learn.pimoroni.com/article/getting-started-with-interstate-75
And: https://github.com/pimoroni/enviro/blob/b5bff82f9001409c9683be43b9f2114e7da8b430/.github/workflows/release-zip.yml#L16
=> CI: Scannable artifact and release names.

.github/workflows/micropython.yml, ci/micropython.sh
Revert our MicroPython builds back to v1.23.0, since "master" currently seems to have a breaky bug, documented here: https://github.com/micropython/micropython/issues/15220
=> TEST: Revert to v1.23.0.

micropython/examples/inky_frame/image_gallery/README.md
As the code exists now, you won't be able to mount the SD card due to the missing import.
=> Add SPI import to SD card upload example

setting-up-the-pico-sdk.md
The preferred method for installing the ARM toolchain has changed. The method currently shown results in a compilation failure:
```
arm-none-eabi-gcc: fatal error: cannot read spec file 'nosys.specs': No such file or directory
```
Refer to [pico-sdk issue 1529](https://github.com/raspberrypi/pico-sdk/issues/1529)
=> Update setup instructions for macOS

drivers/as7343/as7343.cpp, drivers/as7343/as7343.hpp, examples/breakout_as7343/as7343_demo.cpp
The astatus value was being interpreted as FZ, F2 and F1 causing bizarre readings and all other channels to be shifted one place.
Additionally the datasheet has been updated to re-order F5, F7 and F8 to F7, F8, F5, so these channels have been re-ordered accordingly.
Note: This will turn sensor output from confusing abject nonsense into what looks like pretty reasonable colour data and fixes #989.
=> as7343: Fix channel and status order.

micropython/examples/pico_display/scroll_menu_h.py, micropython/examples/pico_display/scroll_menu_v.py
Confirmed ABXY buttons functional on Pico and Pico 2 with Pico Display 2 and 2.8.
Used `machine.Pin ` rather than the `Button` library to maintain compatibility with RP2350 based boards.
=> Pico Display 2.x: Fixed button function

.github/workflows/micropython.yml
Switch from the long deprecated upload-release-asset to action-gh-release and attempt to replicate the same behaviour.
Avoids nodejs and set-output deprecation warnings:
- https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> CI: Switch to action-gh-release.

libraries/pico_graphics/pico_graphics.hpp, libraries/pico_graphics/pico_graphics_pen_rgb565.cpp, micropython/modules/picographics/README.md
I am using a tufty2040 and i wanted to use 565 to show high quality jpegs on my badge, but spritesheets did not work. Simply allowing this and generating a 128x96 Spritesheet (128x128 explodes memory-wise) and using https://github.com/jimmywong2003/PNG-to-RGB565/blob/master/png2rgb565.py with isSWAP=True to create the final spritesheet allows me to have a repeating high quality jpeg character being animated and a high quality spritesheet additionally to show icons, elements and borders.
Please allow this by default, as its the same as the 332 version and it makes my life easier by being able  to use regular releases (current main seems to have broken battery reading)
=> Allow spritesheets for PenRGB565

micropython/examples/plasma_stick/weather.py
The existing weather example was resulting in `OSError: [Errno 12] ENOMEM` when executing subsequent calls to the open-meteo API.
After adding the garbage collection I am no longer seeing these errors and data is being collected as per the timer.
```
Requesting URL: https://api.open-meteo.com/v1/forecast?latitude=**.******&longitude=-*.*******&current_weather=true&timezone=auto
Data obtained!
Temperature = 17.8°C
Conditions = slight rain
Last Open-Meteo update: 2024-07-24, 19:45
Requesting URL: https://api.open-meteo.com/v1/forecast?latitude=**.******&longitude=-*.*******&current_weather=true&timezone=auto
Data obtained!
Temperature = 17.6°C
Conditions = cloudy
Last Open-Meteo update: 2024-07-24, 20:00
Requesting URL: https://api.open-meteo.com/v1/forecast?latitude=**.******&longitude=-*.* …
```
=> Add Garbage Collection to weather example

micropython/examples/pico_lipo_shim/battery_pico.py, micropython/examples/pimoroni_pico_lipo/battery_pico_display.py, micropython/examples/pimoroni_pico_lipo/battery_pico_explorer.py, micropython/examples/tufty2040/autobright.py, micropython/examples/tufty2040/battery.py
=> Examples: Update ADC()

micropython/examples/plasma_stick/cheerlights.py
Makes the default Plasma Stick example a little more conservative with its brightness. This should hopefully stop it from drawing a load of current and making your USB controller fall over if you have an older computer (or are programming it using a Pi :) )
=> add brightness control to default Plasma Stick W example

libraries/pico_graphics/README.md
Spend a good few minutes trying to work out what `s` and `a` did.
"Is `s` scale?"
"Why it it 2 though?"
"`a` is... alpha? No, it defaults to 0..."
"Fine, I'll check the docs."
"That... did not help."
(This could've been avoided if they were called `scale` and `angle` instead...)
I didn't check the rest of the methods.
=> picographics: update text docs

drivers/hub75/hub75.cpp, drivers/hub75/hub75.pio
This adds a delay after latching the row before enabling the output, preventing the annoying ghosting of the next LED's colour onto the previous LED.
=> Hub75: Fix LED ghosting.

micropython/modules_py/pimoroni.py
I just picked up a Pico 2W and GFX Pack to dip my toes into Raspberry Pi microcontrollers. While experimenting, running the button demo didn't work. I stumbled upon a few forum threads and eventually discovered #1041 
This pull request modifies the `Button` class to specify the mode of the `Pin` object created within and, in my testing, this seems to fix the original example/built-in functionality that #1041 bypasses by locally creating `Pin` objects.
**Note:** I don't have the hardware to test this on any other Picos, so I only verified on my Pico 2W.
=> Fix Button class on Pico 2W

README.md
Added a warning about the repo being for RP2040 builds only and a link to the correct repo for RP2350
=> README: Added link to RP2350 repo

libraries/pico_graphics/pico_graphics_pen_p4.cpp
A properly aligned zero length pixel span would cause a single pixel to be drawn, the length overflowed and a subsequent 2GB of pixels drawn by the main loop.
Add a simple check to discard any attempt to draw zero length spans.
Fixes pimoroni/pimoroni-pico-rp2350#32
=> PicoGraphics: Fix overflow bug in p4 pixel span.

drivers/inky73/inky73.cpp, libraries/inky_frame/inky_frame.cpp, libraries/inky_frame_7/inky_frame_7.cpp
While tinkering with my Inky Frame, I noticed that changing the blocking parameter of InkyFrame::update to false has no effect. To be more specific, this is the code I was running (I wanted the status LED to softly pulse while updates are happening to the e-ink display):
```c
frame.update(false);
unsigned int b = 0;
while(frame.is_busy()) {
frame.led(InkyFrame::LED_ACTIVITY, std::min(b, 200 - b));
b = (b + 5) % 200;
sleep_ms(75);
}
frame.led(InkyFrame::LED_ACTIVITY, 0);
```
It turns out that the blocking parameter was being completely ignored in both the inky_frame and inky_frame_7 source files. Thus, I have made a few simple fixes to make the code respect the blocking flag. Also, in inky73.cpp, busy_wait() was called whether or not blocking was set to true or false. I have removed the …
=> Fix: Properly implement non-blocking update functions for the Inky Frame

examples/breakout_as7343/as7343_demo.cpp
Correct the output of the demo:
From `printf("FZ: %d FY: %d FXL: %d NIR: %d F2 %d F3: %d F4: %d F5: %d F1: %d F5: %d F7: %d F8: %d \n",` to
`printf("FZ: %d FY: %d FXL: %d NIR: %d F2 %d F3: %d F4: %d F6: %d F1: %d F5: %d F7: %d F8: %d \n",`
to match the input arguments
=> Correct the output of the as7343 demo

micropython/modules/breakout_scd41/README.md, micropython/modules/breakout_scd41/breakout_scd41.c, micropython/modules/breakout_scd41/breakout_scd41.cpp, micropython/modules/breakout_scd41/breakout_scd41.h
#1056 makes a compelling case for adding these commands in order to avoid sensor drift over time. Here they are ✨
Note: To my future self, don't try to update the Sensiron SCD4X driver submodule until you've got a clear head and a half day to put up with their absolute nonsense.
=> SCD4X: Add calibration commands for #1056.

libraries/pico_vector/alright-fonts.h
Allow find_glyph to find 16-bit unicode codepoints (icons, yay!).
=> PicoVector: Fix find_glyph char to uint16_t.

libraries/pico_vector/alright-fonts.h
This fix resolves #1076
Line breaks in multi-line texts are now handled correctly.
=> Fix line break on text

libraries/pico_vector/alright-fonts.h
The pico vector text renderer skipped over an assumed new line even when the line break was generated by a word wrap.  That meant the first character of the next word was missing.
Found while testing the C presto-boilerplate.
=> Fix skipped character after line wrap

micropython/modules_py/lte.py
Reset the baud rate on the UART on `stop_ppp`, so that it is possible to `start_ppp` again.
Also explicitly set the baudrate to the startup default on init.
=> LTE: Make stop and restart work.
